// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI (migrations) uses the session-mode pooler; the app connects with DATABASE_URL (src/lib/prisma.ts).
    url: process.env["DIRECT_URL"],
  },
});
